/* S-Jiffy timezone-converter 城市数据（78 城，city=英文名 zh=中文名 tz=IANA 时区） */
(function () {
  'use strict';
  window.TZ_CITIES = [
    { city: 'Honolulu', zh: '檀香山', tz: 'Pacific/Honolulu' },
    { city: 'Anchorage', zh: '安克雷奇', tz: 'America/Anchorage' },
    { city: 'Vancouver', zh: '温哥华', tz: 'America/Vancouver' },
    { city: 'Los Angeles', zh: '洛杉矶', tz: 'America/Los_Angeles' },
    { city: 'Phoenix', zh: '凤凰城', tz: 'America/Phoenix' },
    { city: 'Denver', zh: '丹佛', tz: 'America/Denver' },
    { city: 'Mexico City', zh: '墨西哥城', tz: 'America/Mexico_City' },
    { city: 'Chicago', zh: '芝加哥', tz: 'America/Chicago' },
    { city: 'Miami', zh: '迈阿密', tz: 'America/New_York' },
    { city: 'New York', zh: '纽约', tz: 'America/New_York' },
    { city: 'Toronto', zh: '多伦多', tz: 'America/Toronto' },
    { city: 'Montreal', zh: '蒙特利尔', tz: 'America/Toronto' },
    { city: 'Bogota', zh: '波哥大', tz: 'America/Bogota' },
    { city: 'Lima', zh: '利马', tz: 'America/Lima' },
    { city: 'Caracas', zh: '加拉加斯', tz: 'America/Caracas' },
    { city: 'Santiago', zh: '圣地亚哥', tz: 'America/Santiago' },
    { city: 'Sao Paulo', zh: '圣保罗', tz: 'America/Sao_Paulo' },
    { city: 'Buenos Aires', zh: '布宜诺斯艾利斯', tz: 'America/Argentina/Buenos_Aires' },
    { city: 'Lisbon', zh: '里斯本', tz: 'Europe/Lisbon' },
    { city: 'London', zh: '伦敦', tz: 'Europe/London' },
    { city: 'Casablanca', zh: '卡萨布兰卡', tz: 'Africa/Casablanca' },
    { city: 'Madrid', zh: '马德里', tz: 'Europe/Madrid' },
    { city: 'Paris', zh: '巴黎', tz: 'Europe/Paris' },
    { city: 'Berlin', zh: '柏林', tz: 'Europe/Berlin' },
    { city: 'Amsterdam', zh: '阿姆斯特丹', tz: 'Europe/Amsterdam' },
    { city: 'Rome', zh: '罗马', tz: 'Europe/Rome' },
    { city: 'Vienna', zh: '维也纳', tz: 'Europe/Vienna' },
    { city: 'Warsaw', zh: '华沙', tz: 'Europe/Warsaw' },
    { city: 'Stockholm', zh: '斯德哥尔摩', tz: 'Europe/Stockholm' },
    { city: 'Oslo', zh: '奥斯陆', tz: 'Europe/Oslo' },
    { city: 'Copenhagen', zh: '哥本哈根', tz: 'Europe/Copenhagen' },
    { city: 'Helsinki', zh: '赫尔辛基', tz: 'Europe/Helsinki' },
    { city: 'Athens', zh: '雅典', tz: 'Europe/Athens' },
    { city: 'Kyiv', zh: '基辅', tz: 'Europe/Kyiv' },
    { city: 'Bucharest', zh: '布加勒斯特', tz: 'Europe/Bucharest' },
    { city: 'Istanbul', zh: '伊斯坦布尔', tz: 'Europe/Istanbul' },
    { city: 'Moscow', zh: '莫斯科', tz: 'Europe/Moscow' },
    { city: 'Lagos', zh: '拉各斯', tz: 'Africa/Lagos' },
    { city: 'Cape Town', zh: '开普敦', tz: 'Africa/Johannesburg' },
    { city: 'Nairobi', zh: '内罗毕', tz: 'Africa/Nairobi' },
    { city: 'Cairo', zh: '开罗', tz: 'Africa/Cairo' },
    { city: 'Addis Ababa', zh: '亚的斯亚贝巴', tz: 'Africa/Addis_Ababa' },
    { city: 'Jerusalem', zh: '耶路撒冷', tz: 'Asia/Jerusalem' },
    { city: 'Baghdad', zh: '巴格达', tz: 'Asia/Baghdad' },
    { city: 'Riyadh', zh: '利雅得', tz: 'Asia/Riyadh' },
    { city: 'Dubai', zh: '迪拜', tz: 'Asia/Dubai' },
    { city: 'Tehran', zh: '德黑兰', tz: 'Asia/Tehran' },
    { city: 'Karachi', zh: '卡拉奇', tz: 'Asia/Karachi' },
    { city: 'Tashkent', zh: '塔什干', tz: 'Asia/Tashkent' },
    { city: 'Almaty', zh: '阿拉木图', tz: 'Asia/Almaty' },
    { city: 'Mumbai', zh: '孟买', tz: 'Asia/Kolkata' },
    { city: 'Colombo', zh: '科伦坡', tz: 'Asia/Colombo' },
    { city: 'Dhaka', zh: '达卡', tz: 'Asia/Dhaka' },
    { city: 'Yangon', zh: '仰光', tz: 'Asia/Yangon' },
    { city: 'Bangkok', zh: '曼谷', tz: 'Asia/Bangkok' },
    { city: 'Ho Chi Minh', zh: '胡志明市', tz: 'Asia/Ho_Chi_Minh' },
    { city: 'Jakarta', zh: '雅加达', tz: 'Asia/Jakarta' },
    { city: 'Kuala Lumpur', zh: '吉隆坡', tz: 'Asia/Kuala_Lumpur' },
    { city: 'Singapore', zh: '新加坡', tz: 'Asia/Singapore' },
    { city: 'Manila', zh: '马尼拉', tz: 'Asia/Manila' },
    { city: 'Beijing', zh: '北京', tz: 'Asia/Shanghai' },
    { city: 'Shanghai', zh: '上海', tz: 'Asia/Shanghai' },
    { city: 'Hong Kong', zh: '香港', tz: 'Asia/Hong_Kong' },
    { city: 'Taipei', zh: '台北', tz: 'Asia/Taipei' },
    { city: 'Seoul', zh: '首尔', tz: 'Asia/Seoul' },
    { city: 'Tokyo', zh: '东京', tz: 'Asia/Tokyo' },
    { city: 'Osaka', zh: '大阪', tz: 'Asia/Tokyo' },
    { city: 'Novosibirsk', zh: '新西伯利亚', tz: 'Asia/Novosibirsk' },
    { city: 'Vladivostok', zh: '符拉迪沃斯托克', tz: 'Asia/Vladivostok' },
    { city: 'Perth', zh: '珀斯', tz: 'Australia/Perth' },
    { city: 'Adelaide', zh: '阿德莱德', tz: 'Australia/Adelaide' },
    { city: 'Melbourne', zh: '墨尔本', tz: 'Australia/Melbourne' },
    { city: 'Sydney', zh: '悉尼', tz: 'Australia/Sydney' },
    { city: 'Guam', zh: '关岛', tz: 'Pacific/Guam' },
    { city: 'Auckland', zh: '奥克兰', tz: 'Pacific/Auckland' },
    { city: 'Fiji', zh: '斐济', tz: 'Pacific/Fiji' }
  ];
})();
